name: python-sldb-sldb-sldb-selfdoc-python_source_values-frontmatter
path: knowledge/symbols/python-sldb-sldb-sldb-selfdoc-python_source_values-frontmatter.md
hash_c: f93893ac77e13aec921cd59f4ab06916ea7d44fc0ad5da7c858b95c00bd05ef0
hash_d: 78459d9f3861f3aea7b12e5244030100cee379a991b2e671f75a40c72b4ddb60
semantic_tags:
- representation.markdown
- source.code.python
- type.knowledge.code_symbol
- workspace.knowledge.symbols
