name: python-sldb-sldb-sldb-links-composer-compose_document
path: knowledge/symbols/python-sldb-sldb-sldb-links-composer-compose_document.md
hash_c: 721736a3bba9a022703c5ab94d3c76d6949f1078fee7e5bf8354d250f9d1f9f2
hash_d: 3d5268866bd7bc832741214a52772c3c79dd224c9a6aefb4b536e265dde2ccda
semantic_tags:
- representation.markdown
- source.code.python
- type.knowledge.code_symbol
- workspace.knowledge.symbols
