name: python-sldb-sldb-sldb-cli-parsers-legacy-_compose
path: knowledge/symbols/python-sldb-sldb-sldb-cli-parsers-legacy-_compose.md
hash_c: 5c067e6cb59e049a4dafd53f73b56645a2d4941fe08a612daeb93dde5e509d0f
hash_d: 8869a836a5d87abacb9c572239422f92c899afaa68470d79bdce0de82c93bd86
semantic_tags:
- representation.markdown
- source.code.python
- type.knowledge.code_symbol
- workspace.knowledge.symbols
