name: python-sldb-sldb-sldb-selfdoc-values-_json_default
path: knowledge/symbols/python-sldb-sldb-sldb-selfdoc-values-_json_default.md
hash_c: 0c0f6adb8d169b005acebc5155352ce67e3b0784f690a66764053b284ba4820a
hash_d: f0902b6d8ca7f0277ef8b1ebad0aaae2a90dd8eedf8eb116012888a417cfe43f
semantic_tags:
- representation.markdown
- source.code.python
- type.knowledge.code_symbol
- workspace.knowledge.symbols
