"""Typed snapshot of a command or command group."""
from __future__ import annotations

from pydantic import BaseModel, Field
from .argument import ArgumentRecord
from .constraint import ExclusiveGroup


class CommandRecord(BaseModel):
    """Parser-derived facts, distinct from authored documentation prose."""

    path: list[str] = Field(description="Command tokens below the program name.")
    synopsis: str = Field(description="One-line help in the parent parser.")
    description: str = Field(description="Long parser description.")
    usage: str = Field(description="Usage generated by argparse.")
    group: bool = Field(description="Whether this parser has subcommands.")
    hidden: bool = Field(description="Whether this path or an ancestor suppresses help.")
    arguments: list[ArgumentRecord] = Field(description="Local and ancestor arguments.")
    exclusive_groups: list[ExclusiveGroup] = Field(description="Mutual-exclusion rules.")
